language: node_js
node_js: "8.10"
sudo: enabled
branches : 
  only :
    master
before_script :
  - npm i npm@latest -g 
  - npm install -g ionic@latest
  - npm install -g cordova
script :
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master