language: node_js
node_js:
 — “9.2.0”
branches:
 only:
 — master
before_script:
 — npm install -g ionic cordova
script:
 — ionic cordova build browser — prod
deploy:
 provider: pages
 skip-cleanup: true
 github-token: bc527c529a33d4d9d3d4bb3ba5d72dcfd803d95d
 keep-history: true
 on:
   branch: master
 local_dir: www