language: node_js
node_js: stable
sudo: enabled
branches : 
  only :
    master
before_script :
  - sudo npm install -g ionic@lastest
  - sudo npm install -g cordova
script :
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
    on:
      branch: master
