language: node_js
branches:
  only:
  - master
before_script:
  — npm install -g ionic@latest cordova
script:
  — ionic cordova build android --minifycss --optimizejs --minifyjs --release
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
   branch: master
 local_dir: www